name: add_counts_to_isomirs_df
description: Add the sequence counts to the isomiRs dataframe.
keywords:
  - counts
  - isomiR
  - dataframe
  - tsv
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - blast_tsv:
        type: file
        description: |
          TSV file resulting from the combination of BLAST results obtained
          using mature miRNAs and miRNA precursors as references.
    - counts_tsv:
        type: file
        description: |
          Two-column TSV file (sequence, counts) with the counts of each
          nucleotide sequence.
  - - threshold:
        type: integer
        description: |
          Minimum count threshold that a sequence must meet to be considered
          valid. In the resulting file, an additional column indicates 'PASS'
          if the sequence exceeds this threshold or 'REJECT' if it does not.
output:
  - isocounts:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.tsv":
          type: file
          description: |
            TSV file resulting from the combination of BLAST results obtained
            using mature miRNAs and miRNA precursors as references. The file
            includes the counts for each sequence and indicates whether each
            sequence meets the count threshold ('PASS') or not ('REJECT').
          pattern: "*.tsv"
authors:
  - "@antoglz"
maintainers:
  - "@antoglz"
