#!/usr/bin/env nextflow

//
// Subworkflow with functionality specific to the nf-core/rnaseq pipeline
//

workflow PIPELINE_INITIALISATION {
    
    take:

}

// LA FUNCION DE ABAJO LA USAREMOS PARA VALIDAR TODOS LOS PARAMETROS. QUE SE HAYAN
// INTRODUCIDO CORRECTAMENTE. MIRAR ESTA MISMA FUNCION EN NF-CORE RNASEQ. NO HAY
// NINGUN INPUT A LA FUNCION PORQUE A LOS PARAMETROS PODEMOS ACCEDER DESDE
// CUALQUIER SITIO. NOS VA A SERVIR PARA INDICARLE AL USUARIO SI HA METIDO LOS
// PARAMETROS CORRECTAMENTE. POR EJEMPLO. NO PUEDES METER ONLY-PREPROCESSING Y
// FROM-COUNTS.

//
// Check and validate pipeline parameters
//
def validateInputParameters() {

}