name: counts_matrix
description: |
  Create a counts matrix.
keywords:
  - counts
  - rpm
  - matrix
  - quantification
tools:
  - "pandas":
      description: "Python library for data manipulation and analysis"
      homepage: "https://pandas.pydata.org/"
      documentation: "https://pandas.pydata.org/docs/"
      tool_dev_url: "https://github.com/pandas-dev/pandas"
      doi: "10.5281/zenodo.3509134"
      licence: ["BSD-3-Clause"]
      identifiers:
        - "biotools:pandas"
        - "conda:pandas"
  - "numpy":
      description: "NumPy is the fundamental package for scientific computing in Python"
      homepage: "https://numpy.org/"
      documentation: "https://numpy.org/doc/2.2/"
      tool_dev_url: "https://github.com/numpy/numpy"
      doi: "10.1038/s41586-020-2649-2"
      licence: ["BSD-3-Clause"]
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing id information
          e.g. [ id:'PROJECT1_1', species: 'Arabidpsis thaliana', project 'PROJECT1']
    - counts:
        type: file[]
        description: |
          List of files containing either raw counts or RPM values of small RNA
          sequences. Each file consists of two columns: seq and (raw|rpm).
    - metadata:
        type: file
        description: |
          TSV metadata file of the project in question.
  - - type:
        type: string
        description: |
          Specify the type of values used to construct the matrix: raw counts
          or RPM. The value must be either raw or rpm.
  - - not_in_memory:
        type: bool
        description: |
          Specifies that SQLite should use a file on disk rather than
          loading the database into memory when generating the count matrix.
output:
  - gff3:
      - meta:
          type: map
          description: |
            Groovy Map containing id information
            e.g. [ id:'Project' ]
      - "${meta.id}*.{raw,rpm}.tsv":
          type: file
          description: Counts matrix in TSV format.
          pattern: "${meta.id}*.{raw,rpm}.tsv"
  - versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
authors:
  - "@antoglz"
maintainers:
  - "@antoglz"