name: counts_validation
description: |
  Validate counts matrix.
keywords:
  - counts
  - validation
  - matrix
tools:
  - "pandas":
      description: "Python library for data manipulation and analysis"
      homepage: "https://pandas.pydata.org/"
      documentation: "https://pandas.pydata.org/docs/"
      tool_dev_url: "https://github.com/pandas-dev/pandas"
      doi: "10.5281/zenodo.3509134"
      licence: ["BSD-3-Clause"]
      identifiers:
        - "biotools:pandas"
        - "conda:pandas"
  - "numpy":
      description: "NumPy is the fundamental package for scientific computing in Python"
      homepage: "https://numpy.org/"
      documentation: "https://numpy.org/doc/2.2/"
      tool_dev_url: "https://github.com/numpy/numpy"
      doi: "10.1038/s41586-020-2649-2"
      licence: ["BSD-3-Clause"]
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing id information
          e.g. [ id:'PROJECT1', species: 'Arabidpsis thaliana', project 'PROJECT1']
    - counts:
        type: file
        description: |
          Counts matrix in TSV format.
    - metadata:
        type: file
        description: |
          TSV metadata file of the project in question.
    - valid_groups:
        type: val[]
        description: |
          List of valid groups within the project. The project groups are
          specified in the Group column of the metadata file.
  - - rep_threshold:
        type: integer
        description: |
          Minimum number of replicates that the sample groups within a group
          must have to be considered valid.
output:
  - valid:
      - meta:
          type: map
          description: |
            Groovy Map containing id information
            e.g. [ id:'Project' ]
      - "*.valid.tsv":
          type: file
          description: Count matrices in TSV format considered as valid.
          pattern: "*.valid.tsv"
  - notvalid:
      - meta:
          type: map
          description: |
            Groovy Map containing id information
            e.g. [ id:'Project' ]
      - "*.notvalid.tsv":
          type: file
          description: Count matrices in TSV format considered as not-valid.
          pattern: "*.notvalid.tsv"
  - versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
authors:
  - "@antoglz"
maintainers:
  - "@antoglz"