name: rename_file_by_id
description: Rename a file using the 'id' field from the associated metadata map.
keywords:
  - rename
  - metadata
  - file
  - id
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information.
          Must contain an 'id' key, used to rename the file.
          Example: [ id:'sample1' ]
    - file:
        type: file
        description: |
          Input file to be renamed. The file extension will be preserved.
output:
  - renamed:
      - meta:
          type: file
          description: |
            File renamed to match the 'id' field in the input metadata.
            The original file extension is preserved.
          pattern: "*.*"
      - "${meta.id}.*":
          type: file
          description: Renamed file.
          pattern: "*.*"
authors:
  - "@antoniogonzalezsanchez"
maintainers:
  - "@antoniogonzalezsanchez"
