#!/usr/bin/env nextflow

// Specify DSL2
nextflow.enable.dsl=2

// Define the process to execute Prefetch.sh.
process DOWNLOADLIB {

    tag "$meta.species-$meta.project"

    //conda "${modulesDir}/environment.yml"

    input:
    tuple val(meta), path(accession_list)

    output:
    tuple val(meta), path('*.fastq.gz'), emit: fastqgz
    path "versions.yml"                , emit: versions

    script:
    """
    DownloadAndFastqc () {

        local srr="\${1}"
        local species="\${2}"
        local project="\${3}"

        # Temporary directory
        mkdir -p ./tmp

        ############################### prefetch ##################################
        if prefetch --output-directory ./tmp \$srr --verify yes --check-all
        then
            # Check if the SRA file has a .sra or .sralite extension
            if [ -e "./tmp/\$srr/\$srr.sra" ]
            then
                input_file="./tmp/\$srr/\$srr.sra"
            else
                input_file="./tmp/\$srr/\$srr.sralite"
            fi

            ######################### fasterq-dump #################################
            if fasterq-dump --split-files --temp ./tmp -O ./ \$input_file
            then

                # Obtain fastqc data
                if [ -e ./\$srr"_1.fastq" ] && [ -e ./\$srr"_2.fastq" ];
                then
                    # Compress to .gz.
                    pigz ./\$srr"_1.fastq"
                    pigz ./\$srr"_2.fastq"

                else
                    # Compress to .gz.
                    pigz ./\$srr".fastq"

                fi
            else
                # If the fasterq-dump command fails...
                printf "\$species\t\$project\t\$srr\n" >> "./error.txt"
            fi
        else
            # If the prefetch command fails...
            printf "\$species\t\$project\t\$srr\n" >> "./error.txt"
        fi

        # Delete temporary files generated by fasterq-dump.
        rm -r ./tmp
    }

    # Download SRR and obtain fastqc data
    list_of_runs="\$(cat ${accession_list})"

    # iterate through the project's Runs
    for SRR in \$list_of_runs;
    do
        DownloadAndFastqc \$SRR ${meta.species} ${meta.project}
    done

    cat <<-END_VERSIONS > versions.yml
    "${task.process}":
        prefetch: \$( prefetch --version | grep -e 'prefetch' | sed 's/"prefetch" version //' )
        fasterq-dump: \$( fasterq-dump --version | grep -e 'fasterq-dump' | sed 's/"fasterq-dump" version //' )
    END_VERSIONS

    """

    stub:
    """
    touch sample1.fastq.gz
    touch sample2.fastq.gz
    touch sample3.fastq.gz
    touch sample4.fastq.gz
    touch sample5.fastq.gz
    touch sample6.fastq.gz

    cat <<-END_VERSIONS > versions.yml
    "${task.process}":
        prefetch: \$( prefetch --version | grep -e 'prefetch' | sed 's/"prefetch" version //' )
        fasterq-dump: \$( fasterq-dump --version | grep -e 'fasterq-dump' | sed 's/"fasterq-dump" version //' )
    END_VERSIONS
    """
}
