process DOWNLOADLIB {

    tag "$meta.id"

    // conda "${moduleDir}/environment.yml"
    // container "${ workflow.containerEngine == 'singularity' && !task.ext.singularity_pull_docker_container ?
    //     'https://depot.galaxyproject.org/singularity/mulled-v2-5f89fe0cd045cb1d615630b9261a1d17943a9b6a:6a9ff0e76ec016c3d0d27e0c0d362339f2d787e6-0' :
    //     'quay.io/biocontainers/mulled-v2-e0ce9899a3647606dd0b362ef3b857b2f7297da2:0c3da3c7939a976b926534fca505e6d2d4713bae-0' }"

    input:
    tuple val(meta), path(accession_list)

    output:
    tuple val(meta), path('*.fastq.gz'), emit: fastqgz
    path "versions.yml"                , emit: versions

    script:
    """

    DownloadAndFastqc () {

        local srr="\${1}"
        local id="\${2}"

        # Temporary directory
        mkdir -p ./tmp

        ############################### prefetch ##################################
        if prefetch --output-directory ./tmp \$srr --verify yes --check-all
        then
            # Check if the SRA file has a .sra or .sralite extension
            if [ -e "./tmp/\$srr/\$srr.sra" ]
            then
                input_file="./tmp/\$srr/\$srr.sra"
            else
                input_file="./tmp/\$srr/\$srr.sralite"
            fi

            ######################### fasterq-dump #################################
            if fasterq-dump --split-files --temp ./tmp -O ./ \$input_file
            then

                # Obtain fastqc data
                if [ -e ./\$srr"_1.fastq" ] && [ -e ./\$srr"_2.fastq" ];
                then
                    # Compress to .gz.
                    pigz ./\$srr"_1.fastq"
                    pigz ./\$srr"_2.fastq"

                else
                    # Compress to .gz.
                    pigz ./\$srr".fastq"

                fi
            else
                # If the fasterq-dump command fails...
                printf "\$id\t\$srr\n" >> "./error.txt"
            fi
        else
            # If the prefetch command fails...
            printf "\$id\t\$srr\n" >> "./error.txt"
        fi

        # Delete temporary files generated by fasterq-dump.
        rm -r ./tmp
    }

    # Download SRR and obtain fastqc data
    list_of_runs="\$(cat ${accession_list})"

    # iterate through the project's Runs
    for SRR in \$list_of_runs;
    do
        DownloadAndFastqc \$SRR ${meta.id}
    done

    cat <<-END_VERSIONS > versions.yml
    "${task.process}":
        prefetch: \$( prefetch --version | grep -e 'prefetch' | sed 's/"prefetch" version //' )
        fasterq-dump: \$( fasterq-dump --version | grep -e 'fasterq-dump' | sed 's/"fasterq-dump" version //' )
    END_VERSIONS

    """

    stub:
    """
    touch sample1.fastq.gz
    touch sample2.fastq.gz
    touch sample3.fastq.gz
    touch sample4.fastq.gz
    touch sample5.fastq.gz
    touch sample6.fastq.gz

    cat <<-END_VERSIONS > versions.yml
    "${task.process}":
        prefetch: \$( prefetch --version | grep -e 'prefetch' | sed 's/"prefetch" version //' )
        fasterq-dump: \$( fasterq-dump --version | grep -e 'fasterq-dump' | sed 's/"fasterq-dump" version //' )
    END_VERSIONS
    """
}
