#!/usr/bin/env nextflow

// Specify DSL2
nextflow.enable.dsl=2

// Group miRNAs into families.
process GROUP_BY_FAMILY {

    input:
    tuple val(meta), path(dea_file), path(annot_file)

    output:
    path "*fam_annot.tsv", emit: fam_annot
    path "*boxplot.png", emit: fam_boxplot
    path "*summary.tsv", emit: fam_sum

    script:
    """
    07-Group_miRNAs_by_family.r \
        --id ${meta.id} \
        --dea ${dea_file} \
        --annotation ${annot_file}
    """
}

// Combine all summary files generated by GROUP_BY_FAMILY.
process GROUP_BY_FAMILY_SUM {

    input:
    path sum_files

    output:
    path "group_miRNAs_by_family_summary.tsv"

    script:
    """
    cat ${sum_files} > group_miRNAs_by_family_summary.tsv
    sed -i '1iSpecies\tProject\tFile\tnum_total_miRNAs_fam\tnum_miRNAs_dif_trend\tmiRNAs_dif_expresion_trend' group_miRNAs_by_family_summary.tsv
    """
}